markdown: rdiscount
highlighter: true
rdiscount:
  extensions: [smart, autolink]

comments :
   provider: disqus
   disqus:
     short_name: LULU

name: Lulu's blog
description: 喵星人的地盘儿
url: http://howiewang.github.io/lulu
